kind: pipeline
name: default

steps:
- name: build
  image: alpine:3.9.3
  environment:
    VERSION: 2019.09.01
  commands:
    - apk add curl
    - curl -o arch.tar.gz -L https://mirror.yandex.ru/archlinux/iso/$VERSION/archlinux-bootstrap-$VERSION-x86_64.tar.gz
    - rm -rf root.x86_64
    - tar xpzf arch.tar.gz
    - cd root.x86_64
    - tar -czpf ../root.tar.gz *
    - cd ..
    - rm -rf root.x86_64

- name: publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_LOGIN_USERNAME
    password: 
      from_secret: DOCKER_LOGIN_PASSWORD
    repo: burkostya/arch
    tags: 
      - latest
      - 2019-07-01
  when:
    branch:
    - master