kind: pipeline
name: default

steps:
- name: base
  image: alpine:3.9.3
  environment:
    VERSION: 2019.04.01
  commands:
    - apk add curl
    - curl -o arch.tar.gz -L https://mirror.yandex.ru/archlinux/iso/$VERSION/archlinux-bootstrap-$VERSION-x86_64.tar.gz
    - rm -rf root.x86_64
    - tar xpzf arch.tar.gz
    - cd root.x86_64
    - tar -czpf ../root.tar.gz *
    - cd ..
    - rm -rf root.x86_64

- name: build
  image: plugins/docker
  environment:
    # - DOCKER_HOST=unix:///drone/docker.sock
    VERSION: 2019-04-01
    USER:
      from_secret: DOCKER_LOGIN_USERNAME
  settings:
    username: 
      from_secret: DOCKER_LOGIN_USERNAME
    password: 
      from_secret: DOCKER_LOGIN_PASSWORD
    repo: burkostya/arch
    tags: 
      - latest
      - 2019-04-01
  # commands:
  #   - docker build --squash -t burkostya/arch .
  #   - "docker tag burkostya/arch burkostya/arch:${VERSION//\\./-}"
  when:
    branch:
    - master

# services:
# - name: docker
#   image: docker:dind
#   privileged: true
#   command: [ '-H', 'unix:///drone/docker.sock' ]