#!/usr/bin/env bash
set -e

VERSION="$1"

if [ ! -e arch.tar.gz ]; then
    curl -o arch.tar.gz -L https://mirror.yandex.ru/archlinux/iso/$VERSION/archlinux-bootstrap-$VERSION-x86_64.tar.gz
fi

# Remove the trailing "/root.x86_64" from the base image.
if [ ! -e root.tar.gz ]; then
    rm -rf root.x86_64
    tar xpzf arch.tar.gz
    pushd root.x86_64
    tar -czpf ../root.tar.gz *
    popd
    rm -rf root.x86_64
fi

docker build --squash -t burkostya/arch .
echo "${VERSION//\./-}"
docker tag burkostya/arch burkostya/arch:${VERSION//\./-}
